"""Declaration-driven generation tests.

Canonical JSON is the authoritative declaration input. These tests prove the
JSON path directly — deterministic rebuild, source-formatting independence, and
a stable canonical symbolic hash — rather than measuring JSON against the .py
form. Legacy .py equivalence is a migration-only, opt-in check.
"""

from __future__ import annotations

import copy
import json
import os
import subprocess
import sys
from pathlib import Path

from unified import selftest

from unified.boundary import inward
from unified.generator import run_command
from unified.generator.declaration import load_declaration_file
from unified.generator.unfold import _build_tree, _tree_sha256


ROOT = Path(__file__).resolve().parents[1]
DECL = ROOT / "examples" / "declarations" / "text_stats_program.json"
SEEDS = ROOT / "seed" / "declarations"
DECLS = ROOT / "examples" / "declarations"

JSON_DECLARATIONS = [
    DECLS / "text_stats_program.json",
    DECLS / "text_stats_v2.json",
    DECLS / "invoice_total.json",
    SEEDS / "task_ledger.json",
    SEEDS / "score_board.json",
]


def _build_hash(declaration_path: Path, tmp: Path, *, allow_py: bool = False) -> str:
    value = {"declaration_path": str(declaration_path), "project_name": "app"}
    if allow_py:
        value["allow_python_declaration"] = True
    thing = {"value": value, "depths": (), "axes": (), "evidence": (), "state": "formed"}
    out = _build_tree(thing, value, str(tmp))
    assert out.get("state") == "valid", out.get("value")
    return _tree_sha256(Path(out["value"]["project_path"]))


def _reorder_representational_keys(obj, parent_key=None):
    """Reverse dict key order everywhere EXCEPT semantic maps.

    Expression-node keys (op/of/path/error/…) and structural declaration keys
    are representational: their order must not affect generated bytes. Object
    ``fields`` and CSE ``bindings`` are semantic maps (output order / sequential
    evaluation) and keep their insertion order; list order is always preserved.
    """
    if isinstance(obj, dict):
        preserve = parent_key in {"fields", "bindings"}
        keys = list(obj.keys())
        ordered = keys if preserve else list(reversed(keys))
        return {k: _reorder_representational_keys(obj[k], k) for k in ordered}
    if isinstance(obj, list):
        return [_reorder_representational_keys(x, parent_key) for x in obj]
    return obj


@selftest.mark.parametrize("decl", JSON_DECLARATIONS, ids=lambda p: p.stem)
def test_json_declaration_rebuild_is_deterministic(decl, tmp_path):
    """Building the same JSON declaration twice yields byte-identical trees."""
    h1 = _build_hash(decl, tmp_path / "a")
    h2 = _build_hash(decl, tmp_path / "b")
    assert h1 == h2
    assert len(h1) == 64


@selftest.mark.parametrize("decl", JSON_DECLARATIONS, ids=lambda p: p.stem)
def test_json_reordered_keys_are_byte_identical(decl, tmp_path):
    """Reordering representational JSON keys at every nested level is inert.

    Structural canonicalization must not depend on source formatting: a JSON
    declaration with reversed key order at every expression-node and structural
    level must generate the exact same tree.
    """
    raw = json.loads(decl.read_text(encoding="utf-8"))
    perturbed = _reorder_representational_keys(copy.deepcopy(raw))
    # Reordering is content-preserving (dict-equal) but changes serialized key
    # order; assert the perturbation is non-vacuous via the serialized form.
    assert json.dumps(perturbed, ensure_ascii=False) != json.dumps(raw, ensure_ascii=False)
    perturbed_path = tmp_path / "perturbed.json"
    perturbed_path.write_text(json.dumps(perturbed, ensure_ascii=False), encoding="utf-8")

    canonical = _build_hash(decl, tmp_path / "canonical")
    reordered = _build_hash(perturbed_path, tmp_path / "reordered")
    assert canonical == reordered


@selftest.mark.parametrize(
    "decl", [DECLS / "text_stats_v2.json", DECLS / "invoice_total.json"], ids=lambda p: p.stem
)
def test_json_canonical_symbolic_hash_is_stable(decl):
    """Machine symbolic compile of a JSON declaration is deterministic."""
    from unified.machine.compile_decl import compile_declaration_path
    from unified.machine.thing import value_of

    t1 = compile_declaration_path(str(decl))
    t2 = compile_declaration_path(str(decl))
    assert t1.get("state") == "formed", value_of(t1)
    h1 = value_of(t1).get("program_sha256")
    h2 = value_of(t2).get("program_sha256")
    assert h1 and h1 == h2
    assert len(h1) == 64


def test_json_declaration_semantic_output(tmp_path):
    """JSON declaration produces the declared semantic output when run."""
    result = run_command(
        inward(
            {
                "command": "new",
                "name": "uc-invoice-total",
                "parent": str(tmp_path),
                "declaration": str(DECLS / "invoice_total.json"),
            }
        )
    )
    assert result["state"] == "valid", result.get("evidence")
    root = tmp_path / "uc-invoice-total"
    env = {**os.environ, "PYTHONPATH": str(root)}
    doc = root / "invoice.json"
    doc.write_text(
        '{"tax_rate":"0.20","items":['
        '{"quantity":2,"unit_price":"3.50"},{"quantity":1,"unit_price":"4.00"}]}',
        encoding="utf-8",
    )
    proc = subprocess.run(
        [sys.executable, "-m", "uc_invoice_total", str(doc)],
        cwd=str(root),
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )
    assert proc.returncode == 0, proc.stderr + proc.stdout
    out = proc.stdout.replace(" ", "")
    assert '"item_count":2' in out
    assert '"subtotal":"11.00"' in out
    assert '"tax":"2.20"' in out
    assert '"total":"13.20"' in out


@selftest.mark.skipif(
    os.environ.get("UC_ALLOW_PY_DECLARATIONS") != "1",
    reason="legacy Python-declaration equivalence is migration-only (set UC_ALLOW_PY_DECLARATIONS=1)",
)
@selftest.mark.parametrize(
    "stem",
    ["text_stats_program"],
    ids=lambda s: s,
)
def test_legacy_python_equivalence_migration_only(stem, tmp_path):
    """Migration-only: type-clean .py declarations match their JSON twin.

    Only declarations without tuple/list-typed literals in generated test files
    are byte-identical across source forms; v2/invoice diverge cosmetically and
    are intentionally excluded. JSON remains the authoritative form regardless.
    """
    base = DECLS
    json_hash = _build_hash(base / f"{stem}.json", tmp_path / "json")
    py_hash = _build_hash(base / f"{stem}.py", tmp_path / "py", allow_py=True)
    assert json_hash == py_hash


def test_load_text_stats_program_declaration():
    loaded = load_declaration_file(DECL)
    assert loaded["ok"] is True
    assert loaded["kind"] == "program"
    assert loaded["declaration"]["package"] == "uc_text_stats"
    assert len(loaded["declaration"]["features"]) == 2


def test_uc_new_from_declaration_generates_runnable_app(tmp_path):
    result = run_command(
        inward(
            {
                "command": "new",
                "name": "uc-text-stats",
                "parent": str(tmp_path),
                "declaration": str(DECL),
            }
        )
    )
    assert result["state"] == "valid", result.get("evidence")
    assert "generate:new-plan-from-declaration" in result["evidence"]
    root = tmp_path / "uc-text-stats"
    assert (root / "uc_text_stats" / "parts.py").is_file()
    assert (root / "uc_text_stats" / "cli.py").is_file()
    assert (root / "uc_text_stats" / "boundary.py").is_file()
    parts = (root / "uc_text_stats" / "parts.py").read_text(encoding="utf-8")
    assert "def validate_text(" in parts
    assert "def calculate_stats(" in parts
    assert "unique_words" in parts
    assert 'evidence": (*thing["evidence"], "part:validate_text")' not in parts or "validate_text:ok" in parts

    env = {
        **os.environ,
        "PYTHONPATH": os.pathsep.join(
            item
            for item in (str(root), os.environ.get("PYTHONPATH", ""))
            if item
        ),
    }
    sample = root / "sample.txt"
    sample.write_text("Go go GO", encoding="utf-8")
    proc = subprocess.run(
        [sys.executable, "-m", "uc_text_stats", str(sample)],
        cwd=str(root),
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )
    assert proc.returncode == 0, proc.stderr + proc.stdout
    assert '"unique_words":1' in proc.stdout.replace(" ", "")

    proc_t = subprocess.run(
        [sys.executable, str(ROOT / "unified" / "selftest.py")],
        cwd=str(root),
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )
    assert proc_t.returncode == 0, proc_t.stdout + proc_t.stderr


def test_stub_add_still_works_without_declaration(tmp_path):
    created = run_command(
        inward({"command": "new", "name": "stub-app", "parent": str(tmp_path)})
    )
    assert created["state"] == "valid"
    root = tmp_path / "stub-app"
    added = run_command(
        inward(
            {
                "command": "add",
                "name": "mark",
                "project_root": str(root),
            }
        )
    )
    assert added["state"] == "valid"
    assert "generate:add:mark" in added["evidence"]
