"""Render generated project files as plain text data (no filesystem)."""

from __future__ import annotations


def render_new_project(package: str, project_name: str, features: tuple[str, ...]) -> dict[str, str]:
    """Return relative path → file content for a UC-1 project."""
    files: dict[str, str] = {}
    files["pyproject.toml"] = _pyproject(package, project_name)
    files["README.md"] = _readme(package, project_name)
    files[f"{package}/__init__.py"] = _package_init(package)
    files[f"{package}/__main__.py"] = _package_main(package)
    files[f"{package}/boundary.py"] = _boundary()
    files[f"{package}/core.py"] = _core()
    files[f"{package}/features.py"] = _features(features)
    files[f"{package}/parts.py"] = _parts(features)
    files[f"{package}/compose.py"] = _compose(package, features)
    files["tests/test_signature.py"] = _test_signature(package, features)
    files["tests/test_program.py"] = _test_program(package, features)
    return files


def render_add_feature(
    package: str,
    project_name: str,
    existing_features: tuple[str, ...],
    feature: str,
    current_files: dict[str, str],
) -> dict[str, str]:
    """Return the full set of files that must be written for an add."""
    features = (*existing_features, feature)
    updated = dict(current_files)
    updated[f"{package}/features.py"] = _features(features)
    updated[f"{package}/parts.py"] = _parts(features)
    updated[f"{package}/compose.py"] = _compose(package, features)
    updated["tests/test_signature.py"] = _test_signature(package, features)
    updated["tests/test_program.py"] = _test_program(package, features)
    # Preserve pyproject/readme/boundary/core/__init__/__main__ from current.
    return {
        f"{package}/features.py": updated[f"{package}/features.py"],
        f"{package}/parts.py": updated[f"{package}/parts.py"],
        f"{package}/compose.py": updated[f"{package}/compose.py"],
        "tests/test_signature.py": updated["tests/test_signature.py"],
        "tests/test_program.py": updated["tests/test_program.py"],
    }


def _pyproject(package: str, project_name: str) -> str:
    return f"""[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "{project_name}"
version = "0.1.0"
description = "Unified Code UC-1 generated project"
requires-python = ">=3.11"

[tool.unified-code]
generated = true
package = "{package}"
scale = "UC-1"
"""


def _readme(package: str, project_name: str) -> str:
    return f"""# {project_name}

UC-1 project generated by Unified Code.

```bash
python -m {package}
python -m unified.selftest
uc add <feature-name>
```

Developer supplies the meaningful difference inside generated parts.
The generator supplies structure, boundaries, composition, and tests.
"""


def _package_init(package: str) -> str:
    return f'''"""Generated UC-1 package `{package}`."""

from .compose import program
from .features import FEATURES

__all__ = ["FEATURES", "program"]
'''


def _package_main(package: str) -> str:
    return f'''"""Process entry for `{package}`."""

from .boundary import host_render
from .compose import program


def main(thing):
    return program(thing)


if __name__ == "__main__":
    print(host_render(main("seed")))
'''


def _boundary() -> str:
    return '''"""Visible input/output boundaries (L7)."""

THING_FIELDS = ("value", "depths", "axes", "evidence", "state")
STATES = frozenset({"unknown", "absent", "false", "formed", "valid", "invalid"})


def is_thing(obj):
    if not isinstance(obj, dict):
        return False
    if any(field not in obj for field in THING_FIELDS):
        return False
    if not isinstance(obj["depths"], tuple):
        return False
    if not isinstance(obj["axes"], tuple):
        return False
    if not isinstance(obj["evidence"], tuple):
        return False
    if obj["state"] not in STATES:
        return False
    return True


def inward(thing):
    if is_thing(thing):
        return {
            **thing,
            "evidence": (*thing["evidence"], "boundary:inward"),
            "state": "unknown",
        }
    return {
        "value": thing,
        "depths": (),
        "axes": (),
        "evidence": ("boundary:inward",),
        "state": "unknown",
    }


def outward(thing):
    if not is_thing(thing):
        return {
            "value": thing,
            "depths": (),
            "axes": (),
            "evidence": ("boundary:outward", "outward:rejected-non-thing"),
            "state": "invalid",
        }
    return {
        **thing,
        "evidence": (*thing["evidence"], "boundary:outward"),
    }


def host_render(thing):
    from json import dumps

    if not is_thing(thing):
        payload = {
            "value": thing,
            "depths": (),
            "axes": (),
            "evidence": ("host:render-non-thing",),
            "state": "invalid",
        }
        return dumps(payload, indent=2, ensure_ascii=False)
    return dumps({field: thing[field] for field in THING_FIELDS}, indent=2, ensure_ascii=False)
'''


def _core() -> str:
    return '''"""Canonical letter and verify (L1, L5, L6)."""

from .boundary import is_thing


def letter(thing):
    if not is_thing(thing):
        return {
            "value": thing,
            "depths": (),
            "axes": (),
            "evidence": ("letter:rejected-non-thing",),
            "state": "invalid",
        }
    value = thing["value"]
    if value is None:
        state = "absent"
        mark = "letter:absent"
    elif value is False:
        state = "false"
        mark = "letter:false"
    else:
        state = "formed"
        mark = "letter:distinguished"
    return {
        **thing,
        "evidence": (*thing["evidence"], mark),
        "state": state,
    }


def verify(thing):
    if not is_thing(thing):
        return {
            "value": thing,
            "depths": (),
            "axes": (),
            "evidence": ("verify:rejected-non-thing",),
            "state": "invalid",
        }
    # UC-1 script verification: require classification and inward evidence.
    evidence = thing["evidence"]
    has_inward = "boundary:inward" in evidence
    has_letter = any(item.startswith("letter:") for item in evidence)
    ok = has_inward and has_letter and thing["state"] in {"formed", "absent", "false", "valid"}
    return {
        **thing,
        "evidence": (
            *evidence,
            f"script-law:{'pass' if ok else 'fail'}",
        ),
        "state": "valid" if ok else "invalid",
    }
'''


def _features(features: tuple[str, ...]) -> str:
    lines = ["FEATURES = ("]
    for name in features:
        lines.append(f'    "{name}",')
    lines.append(")")
    lines.append("")
    return "\n".join(lines)


def _parts(features: tuple[str, ...]) -> str:
    chunks = [
        '"""Generated transformation parts. Each accepts one thing and returns one thing."""',
        "",
    ]
    for name in features:
        chunks.append(
            f"""def {name}(thing):
    return {{
        **thing,
        "evidence": (*thing["evidence"], "part:{name}"),
    }}
"""
        )
    return "\n".join(chunks)


def _compose(package: str, features: tuple[str, ...]) -> str:
    # Build nested call: outward(verify(fN(...f1(letter(inward(host_value))))))
    expr = "inward(host_value)"
    expr = f"letter({expr})"
    for name in features:
        expr = f"{name}({expr})"
    expr = f"verify({expr})"
    expr = f"outward({expr})"
    imports = ", ".join(features) if features else ""
    import_line = (
        f"from .parts import {imports}" if features else "from . import parts  # noqa: F401"
    )
    return f'''"""Nested composition of generated parts (L2)."""

from .boundary import inward, outward
from .core import letter, verify
{import_line}


def program(host_value):
    return {expr}
'''


def _test_signature(package: str, features: tuple[str, ...]) -> str:
    feature_list = ", ".join(f"parts.{name}" for name in features)
    return f'''from inspect import Parameter, signature

from {package} import compose, parts
from {package}.boundary import inward, outward
from {package}.core import letter, verify
from {package}.features import FEATURES


def test_features_tuple_matches_parts():
    assert FEATURES == {features!r}
    for name in FEATURES:
        assert callable(getattr(parts, name))


def test_every_public_operation_has_one_input():
    operations = (
        letter,
        verify,
        inward,
        outward,
        compose.program,
        {feature_list}
    )
    for operation in operations:
        if operation is None:
            continue
        parameters = tuple(signature(operation).parameters.values())
        assert len(parameters) == 1
'''


def _test_program(package: str, features: tuple[str, ...]) -> str:
    part_asserts = "\n".join(
        f'    assert "part:{name}" in result["evidence"]' for name in features
    )
    return f'''from {package}.compose import program
from {package}.features import FEATURES


def test_program_runs_and_is_valid():
    result = program("seed")
    assert result["state"] == "valid"
    assert result["value"] == "seed"
    assert "boundary:inward" in result["evidence"]
    assert "boundary:outward" in result["evidence"]
    assert "letter:distinguished" in result["evidence"]
{part_asserts}
    assert list(FEATURES) == list({features!r})


def test_unknown_absent_false_distinct():
    from {package}.boundary import inward
    from {package}.core import letter

    unknown = inward("x")
    absent = letter(inward(None))
    false = letter(inward(False))
    assert unknown["state"] == "unknown"
    assert absent["state"] == "absent"
    assert false["state"] == "false"
    assert len({{unknown["state"], absent["state"], false["state"]}}) == 3
'''
